# Generated by Django 5.2.8 on 2025-11-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skinrecord',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='skin_records/'),
        ),
        migrations.AlterField(
            model_name='skinrecord',
            name='memo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
