# Generated by Django 5.2.8 on 2025-11-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_skinrecord_image_alter_skinrecord_memo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skinrecord',
            options={'ordering': ['-date'], 'verbose_name': '肌記録', 'verbose_name_plural': '肌記録'},
        ),
        migrations.AlterField(
            model_name='skinrecord',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
